#!/bin/sh
# $Id: backpasswd.sh,v 1.3 2000/08/01 04:19:17 davidyu Exp $

mv PASSWDS.NEW5 PASSWDS.NEW6
mv PASSWDS.NEW4 PASSWDS.NEW5
mv PASSWDS.NEW3 PASSWDS.NEW4
mv PASSWDS.NEW2 PASSWDS.NEW3
mv PASSWDS.NEW1 PASSWDS.NEW2
mv PASSWDS.NEW  PASSWDS.NEW1
cp .PASSWDS PASSWDS.NEW

